//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayiOA.Entities.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public Groups()
        {
            this.GroupMessages = new HashSet<GroupMessages>();
            this.GroupNotice = new HashSet<GroupNotice>();
            this.GroupResources = new HashSet<GroupResources>();
            this.GroupUsers = new HashSet<GroupUsers>();
        }
    
        public int GroupID { get; set; }
        public int ClientID { get; set; }
        public string GroupName { get; set; }
        public string GroupType { get; set; }
        public bool IsHidden { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string LastModifyBy { get; set; }
        public Nullable<System.DateTime> LastModifyOn { get; set; }
        public Nullable<bool> SoftDelete { get; set; }
        public int CreateUserID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<GroupMessages> GroupMessages { get; set; }
        public virtual ICollection<GroupNotice> GroupNotice { get; set; }
        public virtual ICollection<GroupResources> GroupResources { get; set; }
        public virtual ICollection<GroupUsers> GroupUsers { get; set; }
        public virtual Users Users { get; set; }
    }
}
