//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayiOA.Entities.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupNotice
    {
        public GroupNotice()
        {
            this.GroupNoticeComments = new HashSet<GroupNoticeComments>();
        }
    
        public int GroupNoticeID { get; set; }
        public int ClientID { get; set; }
        public int GroupID { get; set; }
        public string NoticeContent { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string LastModifyBy { get; set; }
        public Nullable<System.DateTime> LastModifyOn { get; set; }
        public Nullable<bool> SoftDelete { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual ICollection<GroupNoticeComments> GroupNoticeComments { get; set; }
    }
}
