//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayiOA.Entities.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupUsers
    {
        public int UserID { get; set; }
        public int GroupID { get; set; }
        public int ClientID { get; set; }
        public bool IsAdmin { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
