//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayiOA.Entities.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MayiOAEntities : DbContext
    {
        public MayiOAEntities()
            : base("name=MayiOAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clients> Clients { get; set; }
        public DbSet<GroupMessages> GroupMessages { get; set; }
        public DbSet<GroupNotice> GroupNotice { get; set; }
        public DbSet<GroupNoticeComments> GroupNoticeComments { get; set; }
        public DbSet<GroupResources> GroupResources { get; set; }
        public DbSet<Groups> Groups { get; set; }
        public DbSet<GroupUsers> GroupUsers { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
