//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayiOA.Entities.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Groups = new HashSet<Groups>();
        }
    
        public int UserID { get; set; }
        public int ClientID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string NickName { get; set; }
        public string FullName { get; set; }
        public string Avatar { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string JobTitle { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public int Status { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string LastModifyBy { get; set; }
        public Nullable<System.DateTime> LastModifyOn { get; set; }
        public Nullable<bool> SoftDelete { get; set; }
        public string QQ { get; set; }
        public string Weibo { get; set; }
        public string Wechat { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<Groups> Groups { get; set; }
    }
}
